defautWait = 30
xpathMail = '//main/article/div[2]/div[1]/div/form/div/div[1]/div/label/input | //main/div/div/div[1]/div/form/div/div[1]/div/label/input'
xpathPass = '//main/div/div/div[1]/div/form/div/div[2]/div/label/input | //main/article/div[2]/div[1]/div/form/div/div[2]/div/label/input'
xpathButtonLogin = '//main/div/div/div[1]/div/form/div/div[3] | //main/article/div[2]/div[1]/div/form/div/div[3]'
notNowButtonSaveInfo = "//body/div[1]/section/main/div/div/div/div/button"
notNowButtonNotification = "//body/div[4]/div/div/div/div[3]/button[2]"
userName = 'nguyenminhtri644'
passWord = "Tri123456"
cookies_file = "cookies_integram.pkl"
